=== fsufitch/jdip/jdip_16_17/resource/common/dtd/variants.dtd
<!ELEMENT VARIANTS (DESCRIPTION, MAP_DEFINITION+, VARIANT+)>

<!ELEMENT DESCRIPTION (#PCDATA)>

<!ELEMENT MAP_DEFINITION (DESCRIPTION?)>
<!ATTLIST MAP_DEFINITION 
	id ID #REQUIRED
	title CDATA #REQUIRED
	URI CDATA #REQUIRED
	thumbURI CDATA #REQUIRED
	preferredUnitStyle CDATA #IMPLIED
	>

<!ELEMENT VARIANT (DESCRIPTION, MAP, RULEOPTIONS?, POWER+, STARTINGTIME, VICTORYCONDITIONS, SUPPLYCENTER+, INITIALSTATE*)>
<!ATTLIST VARIANT
		name CDATA #REQUIRED
		default (true|false) "false"
		version CDATA #REQUIRED
		aliases CDATA #IMPLIED
		>
		
<!ELEMENT MAP (MAP_GRAPHIC*)>
<!ATTLIST MAP adjacencyURI CDATA #REQUIRED>

<!ELEMENT MAP_GRAPHIC EMPTY>
<!ATTLIST MAP_GRAPHIC
		ref IDREF #REQUIRED
		default (true|false) "false"
		preferredUnitStyle CDATA #IMPLIED
		>

<!ELEMENT RULEOPTIONS (RULEOPTION+)>
<!ELEMENT RULEOPTION EMPTY>
<!ATTLIST RULEOPTION	name CDATA #REQUIRED
			value CDATA #REQUIRED>

<!ELEMENT POWER EMPTY>
<!ATTLIST POWER name CDATA #REQUIRED
		active (true|false) "true"
		adjective CDATA #REQUIRED
		altnames CDATA #IMPLIED
		>

<!ELEMENT STARTINGTIME EMPTY>
<!ATTLIST STARTINGTIME 	turn CDATA #REQUIRED
			allowBCYears (true|false) "false"
			>

<!ELEMENT VICTORYCONDITIONS (WINNING_SUPPLY_CENTERS?, YEARS_WITHOUT_SC_CAPTURE?, GAME_LENGTH?)>

<!ELEMENT WINNING_SUPPLY_CENTERS EMPTY>
<!ATTLIST WINNING_SUPPLY_CENTERS value CDATA #REQUIRED>

<!ELEMENT YEARS_WITHOUT_SC_CAPTURE EMPTY>
<!ATTLIST YEARS_WITHOUT_SC_CAPTURE value CDATA #REQUIRED>

<!ELEMENT GAME_LENGTH EMPTY>
<!ATTLIST GAME_LENGTH value CDATA #REQUIRED>

<!ELEMENT SUPPLYCENTER EMPTY>
<!ATTLIST SUPPLYCENTER 	province CDATA #REQUIRED
			homepower CDATA "none"
			owner CDATA "none"
			>
			
<!ELEMENT INITIALSTATE EMPTY>
<!ATTLIST INITIALSTATE 	province CDATA #REQUIRED
			power CDATA #REQUIRED
			unit CDATA #REQUIRED
			unitcoast CDATA #IMPLIED
			>

=== fsufitch/jdip/jdip_16_17/resource/variants/asia/variants.xml
<?xml version="1.0"?>
<!DOCTYPE VARIANTS PUBLIC "-//JDIP//VARIANTS DTD//1.0//DEFAULT" "http://jdip.sourceforge.net/dtd/variants.dtd">
<VARIANTS>
	<DESCRIPTION><![CDATA[Created variant.]]></DESCRIPTION> 
	
	<MAP_DEFINITION id="defaultMap" title="Asia" preferredUnitStyle="modern"
		URI="asia.svg" thumbURI="asia_thumb.png">
		<DESCRIPTION><![CDATA[
			Asia variant map.
		]]>
		</DESCRIPTION> 
	</MAP_DEFINITION>
	
	<VARIANT name="Asia" version="1.0">
		<DESCRIPTION><![CDATA[
		<p>
			Asian Diplomacy was originally conceived of and created by David Lawler,
			updated and modified by Peter Baer.  Territory chart revised by Will Wible. 
		</p>
		<p>
			There are absolutely no rule changes from the standard rulebook.
			Just a new map.  Canals are similar to Constantinople in the regular
			game; ie fleets and armies may cross, but only one may be occupying
			the territory at a time. Asian Diplomacy has almost no historical basis.
		</p>
		<p>
			Authors: David Lawler, Peter Baer and Will Wible<br>
			Map by: Stephen McKee
		</p>
		]]>
		</DESCRIPTION> 
		<MAP adjacencyURI="asia_adjacency.xml">
			<MAP_GRAPHIC ref="defaultMap" default="true" />
		</MAP>
		
		<!-- ruleoptions -->
		<RULEOPTIONS>
			<RULEOPTION name="OPTION_BUILDS" value="VALUE_BUILDS_HOME_ONLY"/>
		</RULEOPTIONS>
		
		<!-- powers -->
		<POWER name="China" 		active="true" adjective="Chinese" 	 />	<!-- C -->
		<POWER name="India" 		active="true" adjective="Indian" 	 />	<!-- N -->
		<POWER name="Indonesia" 	active="true" adjective="Indonesian" />	<!-- I -->
		<POWER name="Japan" 		active="true" adjective="Japanese" 	 />	<!-- J -->
		<POWER name="Persia" 		active="true" adjective="Persian" 	 />	<!-- P -->
		<POWER name="Russia" 		active="true" adjective="Russian" 	 />	<!-- R -->
		<POWER name="Siberia" 	    active="true" adjective="Siberian" 	 />	<!-- S -->

		<!-- starting time -->
		<STARTINGTIME turn="Spring, 1901, Movement" />
		
		<!-- victory conditions -->
		<VICTORYCONDITIONS>
			<WINNING_SUPPLY_CENTERS value="21"/>
		</VICTORYCONDITIONS>
 	 	
		<!-- supply centers -->
		<SUPPLYCENTER province="ara" homepower="persia" owner="persia"/>
		<SUPPLYCENTER province="aus"/>
		<SUPPLYCENTER province="bal"/>
		<SUPPLYCENTER province="ban"/>
		<SUPPLYCENTER province="bjg" homepower="china" owner="china"/>
		<SUPPLYCENTER province="bom" homepower="india" owner="india"/>
		<SUPPLYCENTER province="bor" homepower="indonesia" owner="indonesia"/>
		<SUPPLYCENTER province="cal" homepower="india" owner="india"/>
		<SUPPLYCENTER province="del" homepower="india" owner="india"/>
		<SUPPLYCENTER province="egy"/>
		<SUPPLYCENTER province="hok" homepower="japan" owner="japan"/>
		<SUPPLYCENTER province="hon" homepower="japan" owner="japan"/>
		<SUPPLYCENTER province="irk" homepower="siberia" owner="siberia"/>
		<SUPPLYCENTER province="irn" homepower="persia" owner="persia"/>
		<SUPPLYCENTER province="irq" homepower="persia" owner="persia"/>
		<SUPPLYCENTER province="jav" homepower="indonesia" owner="indonesia"/>
		<SUPPLYCENTER province="kam" homepower="siberia" owner="siberia"/>
		<SUPPLYCENTER province="lao"/>
		<SUPPLYCENTER province="mad"/>
		<SUPPLYCENTER province="man" homepower="japan" owner="japan"/>
		<SUPPLYCENTER province="mos" homepower="russia" owner="russia"/>
		<SUPPLYCENTER province="new"/>
		<SUPPLYCENTER province="nov"/>
		<SUPPLYCENTER province="oma"/>
		<SUPPLYCENTER province="pak"/>
		<SUPPLYCENTER province="phi" homepower="japan" owner="japan"/>
		<SUPPLYCENTER province="sev" homepower="russia" owner="russia"/>
		<SUPPLYCENTER province="sha" homepower="china" owner="china"/>
		<SUPPLYCENTER province="sri"/>
		<SUPPLYCENTER province="stp" homepower="russia" owner="russia"/>
		<SUPPLYCENTER province="sum" homepower="indonesia" owner="indonesia"/>
		<SUPPLYCENTER province="tha"/>
		<SUPPLYCENTER province="tia"/>
		<SUPPLYCENTER province="tib" homepower="china" owner="china"/>
		<SUPPLYCENTER province="tur"/>
		<SUPPLYCENTER province="ura"/>
		<SUPPLYCENTER province="uzb"/>
		<SUPPLYCENTER province="vie"/>
		<SUPPLYCENTER province="wsb" homepower="siberia" owner="siberia"/>
		<SUPPLYCENTER province="yak"/>
		
		<!-- unit placement -->
		<INITIALSTATE province="bei" 	power="china" 		unit="army"/>
		<INITIALSTATE province="tib" 	power="china" 		unit="army"/>
		<INITIALSTATE province="sha" 	power="china" 		unit="fleet"/>
		<INITIALSTATE province="cal" 	power="india" 		unit="army"/>
		<INITIALSTATE province="del" 	power="india" 		unit="army"/>
		<INITIALSTATE province="bom" 	power="india" 		unit="fleet"/>
		<INITIALSTATE province="bor" 	power="indonesia" 	unit="fleet"/>
		<INITIALSTATE province="jav" 	power="indonesia" 	unit="fleet"/>
		<INITIALSTATE province="sum" 	power="indonesia" 	unit="fleet"/>
		<INITIALSTATE province="hok" 	power="japan" 		unit="fleet"/>
		<INITIALSTATE province="hon" 	power="japan" 		unit="fleet"/>
		<INITIALSTATE province="man" 	power="japan" 		unit="army"/>
		<INITIALSTATE province="phi" 	power="japan" 		unit="fleet"/>
		<INITIALSTATE province="irn" 	power="persia" 		unit="army"/>
		<INITIALSTATE province="irq" 	power="persia" 		unit="army"/>
		<INITIALSTATE province="ara" 	power="persia" 		unit="fleet" unitcoast="ec"/>
		<INITIALSTATE province="mos" 	power="russia" 		unit="army"/>
		<INITIALSTATE province="sev" 	power="russia" 		unit="army"/>
		<INITIALSTATE province="stp" 	power="russia" 		unit="fleet"/>
		<INITIALSTATE province="irk" 	power="siberia" 	unit="army"/>
		<INITIALSTATE province="kam" 	power="siberia" 	unit="fleet"/>
		<INITIALSTATE province="wes" 	power="siberia" 	unit="army"/>
	</VARIANT>
</VARIANTS>

=== fsufitch/jdip/jdip_16_17/resource/variants/pure/variants.xml
<?xml version="1.0"?>
<!DOCTYPE VARIANTS PUBLIC "-//JDIP//VARIANTS DTD//1.0//DEFAULT" "http://jdip.sourceforge.net/dtd/variants.dtd">
<VARIANTS>
	<DESCRIPTION><![CDATA[<div style="font-family:arial,helvetica;">
	Pure Variant
	</div>]]></DESCRIPTION>
	
	<MAP_DEFINITION id="pure" title="Pure" 
		URI="pure.svg" thumbURI="pure_thumb.png" preferredUnitStyle="period">
		<DESCRIPTION>
		A stylized map for the Pure variant.
		</DESCRIPTION>
	</MAP_DEFINITION>

	
	<VARIANT name="Pure" version="1.0">
		<DESCRIPTION><![CDATA[
		This is a simple traditional variant of diplomacy. There are the usual
		seven countries. There are seven spaces on the board--one
		corresponding to each country--its home supply center. These spaces
		are all connected by land one with another. Initially, each player
		begins with one army in his home supply center.
		<p>
		The objective of the game is to accumulate four supply centers
		</p>
		<p style="margin-top:21pt;">Author: Danny Loeb</p>]]></DESCRIPTION> 
		<MAP adjacencyURI="pure_adjacency.xml">
			<MAP_GRAPHIC ref="pure" default="true" />
		</MAP>
		<RULEOPTIONS>
			<RULEOPTION name="OPTION_BUILDS" value="VALUE_BUILDS_HOME_ONLY" />
		</RULEOPTIONS>
		<POWER name="Austria" active="true" adjective="Austrian" /> 
		<POWER name="England" active="true" adjective="English" altnames="Britain" /> 
		<POWER name="France" active="true" adjective="French" /> 
		<POWER name="Germany" active="true" adjective="German" /> 
		<POWER name="Italy" active="true" adjective="Italian" />
		<POWER name="Russia" active="true" adjective="Russian" /> 
		<POWER name="Turkey" active="true" adjective="Turkish" /> 
		<STARTINGTIME turn="Spring, 1914, Movement" />
		<VICTORYCONDITIONS>
			<WINNING_SUPPLY_CENTERS value="4" />
			<YEARS_WITHOUT_SC_CAPTURE value="7" />
			<GAME_LENGTH value="35" />
		</VICTORYCONDITIONS>
 	 	<!-- supply centers -->
		<SUPPLYCENTER province="vie" homepower="austria" owner="austria"/>
		<SUPPLYCENTER province="lon" homepower="england" owner="england"/>
		<SUPPLYCENTER province="par" homepower="france" owner="france"/>
		<SUPPLYCENTER province="ber" homepower="germany" owner="germany"/>
		<SUPPLYCENTER province="rom" homepower="italy" owner="italy"/>
		<SUPPLYCENTER province="mos" homepower="russia" owner="russia"/>
		<SUPPLYCENTER province="con" homepower="turkey" owner="turkey"/>
		<!-- unit placement -->
		<INITIALSTATE province="vie" power="austria" unit="army" />
		<INITIALSTATE province="lon" power="england" unit="army" />
		<INITIALSTATE province="par" power="france" unit="army" />
		<INITIALSTATE province="ber" power="germany" unit="army" />
		<INITIALSTATE province="rom" power="italy" unit="army" />
		<INITIALSTATE province="mos" power="russia" unit="army" />
		<INITIALSTATE province="con" power="turkey" unit="army" />
	</VARIANT>
</VARIANTS>

=== fsufitch/jdip/jdip_16_17/resource/variants/octarine/variants.xml
<?xml version="1.0"?>
<!DOCTYPE VARIANTS PUBLIC "-//JDIP//VARIANTS DTD//1.0//DEFAULT" "http://jdip.sourceforge.net/dtd/variants.dtd">
<VARIANTS>
	<DESCRIPTION><![CDATA[The main variant list for jDip]]></DESCRIPTION> 
	
	<MAP_DEFINITION id="standard" title="Standard" preferredUnitStyle="period" URI="octarine.svg" thumbURI="octarine_thumb.png">
		<DESCRIPTION>The traditional Octarine map.</DESCRIPTION>
	</MAP_DEFINITION>
	
	
	<VARIANT name="Octarine" version="0.06" default="true">
		<DESCRIPTION><![CDATA[
		<p>
			This is version 0.06 (Ogg) of the Octarine Diplomacy variant, 
			an 8-player variant for Diplomacy based on Terry Pratchett's 
			Discworld.
		</p>
		<p>
			Standard Diplomacy rules are used and only the map 
			(with some special provinces) has been changed.
		</p>
		<h2>Special provinces:</h2>
		<div class="indent1cm">
			<p>
				The Celestial Straits between Agatea and the main continent are
				frozen in Winter. Therefore, fleets may only pass through in Spring,
				whilst armies may cross in Autumn. Specifically: In Spring, PEL and WWO 
				are adjacent, LIG and Ctk are not. In Autumn, LIG and Ctk are adjacent,
				PEL and WWO are not. No coastal designations are required for fleets in 
				LIG or Ctk; it is assumed that a fleet in these provinces can keep a 
				channel open through Winter if necessary, but that there is not time 
				for a fleet to open a channel directly from PEL to WWO and move through 
				it in one turn.
			</p>
			<p>
				Due to the edicts carved in the ancient stone of Djelibeybi, 
				no foreign military units are allowed to occupy or traverse 
				Djelibeybi or its coastal waters. There is therefore no direct 
				movement whatsoever between Ephebe and Tsort.
				</p>
			<p>
				The provinces of beTrobi Islands, Brown Islands, Land of Fog, 
				and Purdeighsland, are normal coastal provinces - they may be occupied 
				by an army (convoyed there) or a fleet. A fleet in any of them may not 
				take part in a convoy.
			</p>
			<p>
				Ku is a special sea supply centre. Ku may only be occupied by a 
				fleet, and a fleet there may be involved in a convoy.
			</p>
			<p>
				The provinces of Purdeighsland and Terror Incognita are treated 
				as Sweden and Denmark are in standard Diplomacy. Armies and fleets 
				may move freely between them. Also, the coast of Terror Incognita 
				from Hubwards New Llamedos past The Big Bight, Purdeighsland, and 
				the Rimwards Widdershins Ocean to the edge of the map is a single 
				coast--the Hubwards coast.
			</p>
		</div>
		<p style="margin-top:21pt;">
			Authors: Jake N Aard and Gary Duke<br>
			Electronic map by Bjrn Lijnema
		</p>]]></DESCRIPTION> 
		
		<MAP adjacencyURI="octarine_adjacency.xml">
			<MAP_GRAPHIC ref="standard" default="true" />
		</MAP>
		
		<RULEOPTIONS>
			<RULEOPTION name="OPTION_BUILDS" value="VALUE_BUILDS_HOME_ONLY" />
		</RULEOPTIONS>
		
		<POWER name="Ogg" active="true" adjective="Oggish" /> 
		<POWER name="XXXX" active="true" adjective="Foureksian" /> 
		<POWER name="Genua" active="true" adjective="Genuan" /> 
		<POWER name="Klatch" active="true" adjective="Klatchian" /> 
		<POWER name="Muntab" active="true" adjective="Muntabi" /> 
		<POWER name="Morpork" active="true" adjective="Morporkian" /> 
		<POWER name="Agatea" active="true" adjective="Agatean" />
		<POWER name="Hublands" active="true" adjective="Hublandish" />
		<STARTINGTIME turn="Spring, 01, Movement" />
		
		<VICTORYCONDITIONS>
			<WINNING_SUPPLY_CENTERS value="22" />
		</VICTORYCONDITIONS>

		<SUPPLYCENTER province="ank" homepower="Morpork" owner="Morpork"/>
		<SUPPLYCENTER province="bes" homepower="Agatea" owner="Agatea"/>
		<SUPPLYCENTER province="bla" homepower="Genua" owner="Genua"/>
		<SUPPLYCENTER province="bor" />
		<SUPPLYCENTER province="bri" homepower="Muntab" owner="Muntab"/>
		<SUPPLYCENTER province="bro" />
		<SUPPLYCENTER province="bti" />
		<SUPPLYCENTER province="chi" homepower="Ogg" owner="Ogg"/>
		<SUPPLYCENTER province="ctk" />
		<SUPPLYCENTER province="eph" homepower="Morpork" owner="Morpork"/>
		<SUPPLYCENTER province="gen" homepower="Genua" owner="Genua"/>
		<SUPPLYCENTER province="gha" homepower="Muntab" owner="Muntab"/>
		<SUPPLYCENTER province="hng" homepower="Agatea" owner="Agatea"/>
		<SUPPLYCENTER province="hnl" homepower="XXXX" owner="XXXX"/>
		<SUPPLYCENTER province="how" homepower="Klatch" owner="Klatch"/>
		<SUPPLYCENTER province="hub" homepower="Hublands" owner="Hublands"/>
		<SUPPLYCENTER province="ing" homepower="Hublands" owner="Hublands"/>
		<SUPPLYCENTER province="kha" homepower="Klatch" owner="Klatch"/>
		<SUPPLYCENTER province="kru" />
		<SUPPLYCENTER province="ku" />
		<SUPPLYCENTER province="kyt" homepower="Genua" owner="Genua"/>
		<SUPPLYCENTER province="lan" homepower="Ogg" owner="Ogg"/>
		<SUPPLYCENTER province="lla" homepower="Ogg" owner="Ogg"/>
		<SUPPLYCENTER province="lof" />
		<SUPPLYCENTER province="mom" />
		<SUPPLYCENTER province="mun" homepower="Muntab" owner="Muntab"/>
		<SUPPLYCENTER province="naf" />
		<SUPPLYCENTER province="nef" />
		<SUPPLYCENTER province="not" />
		<SUPPLYCENTER province="omn" homepower="Morpork" owner="Morpork"/>
		<SUPPLYCENTER province="pur" homepower="XXXX" owner="XXXX"/>
		<SUPPLYCENTER province="red" homepower="Klatch" owner="Klatch"/>
		<SUPPLYCENTER province="reh" homepower="Muntab" owner="Muntab"/>
		<SUPPLYCENTER province="sdi" homepower="Agatea" owner="Agatea"/>
		<SUPPLYCENTER province="ter" homepower="XXXX" owner="XXXX"/>
		<SUPPLYCENTER province="tez" />
		<SUPPLYCENTER province="tso" />
		<SUPPLYCENTER province="ube" />
		<SUPPLYCENTER province="ura" />
		<SUPPLYCENTER province="ush" />
		<SUPPLYCENTER province="vor" homepower="Hublands" owner="Hublands"/>
		<SUPPLYCENTER province="wyr" />


		<INITIALSTATE province="ank" power="Morpork" unit="fleet" />
		<INITIALSTATE province="bes" power="Agatea" unit="fleet" />
		<INITIALSTATE province="bla" power="Genua" unit="fleet" />
		<INITIALSTATE province="bri" power="Muntab" unit="fleet" />
		<INITIALSTATE province="chi" power="Ogg" unit="fleet" />
		<INITIALSTATE province="eph" power="Morpork" unit="army" />
		<INITIALSTATE province="gen" power="Genua" unit="army" />
		<INITIALSTATE province="gha" power="Muntab" unit="army" />
		<INITIALSTATE province="how" power="Klatch" unit="army" />
		<INITIALSTATE province="hng" power="Agatea" unit="fleet" />
		<INITIALSTATE province="hnl" power="XXXX" unit="fleet" />
		<INITIALSTATE province="hub" power="Hublands" unit="army" />
		<INITIALSTATE province="ing" power="Hublands" unit="fleet" />
		<INITIALSTATE province="kha" power="Klatch" unit="fleet" />
		<INITIALSTATE province="kyt" power="Genua" unit="fleet" />
		<INITIALSTATE province="lan" power="Ogg" unit="army" />
		<INITIALSTATE province="lla" power="Ogg" unit="army" />
		<INITIALSTATE province="mun" power="Muntab" unit="army" />
		<INITIALSTATE province="omn" power="Morpork" unit="army" />
		<INITIALSTATE province="pur" power="XXXX" unit="fleet" />
		<INITIALSTATE province="red" power="Klatch" unit="army" />
		<INITIALSTATE province="reh" power="Muntab" unit="fleet" unitcoast="ec" />
		<INITIALSTATE province="sdi" power="Agatea" unit="fleet" unitcoast="nc" />
		<INITIALSTATE province="ter" power="XXXX" unit="fleet" unitcoast="sc" />
		<INITIALSTATE province="vor" power="Hublands" unit="army" />
	</VARIANT>
</VARIANTS>

=== fsufitch/jdip/jdip_16_17/resource/variants/chaos_dp/variants.xml
<?xml version="1.0"?>
<!DOCTYPE VARIANTS PUBLIC "-//JDIP//VARIANTS DTD//1.0//DEFAULT" "http://jdip.sourceforge.net/dtd/variants.dtd">
<VARIANTS>
	<DESCRIPTION><![CDATA[The main variant list for jDip]]></DESCRIPTION> 
	
	<MAP_DEFINITION id="chaos" title="Standard"  preferredUnitStyle="modern"
		URI="chaos.svg" thumbURI="chaos_thumb.png">
		<DESCRIPTION>
		The traditional map, optimized for Chaos games.
		</DESCRIPTION>
	</MAP_DEFINITION>
	
	
	<VARIANT name="Chaos (DPJudge)" version="2.0" default="false">
		<DESCRIPTION><![CDATA[ 
		<p>
			This version of Chaos is compatible with <b>DPJudge</b>-based
			judges, such as USDP and UKDP. It is not compatible with 
			nJudge-based judges.
		</p>
		<p>
			The chaos variant is played by 34 players, each owning a single supply
			center on the standard map.  The game starts in Winter of
			1900 at the adjustment phase.  Each player starts out choosing which
			type of unit they wish to build and progressing from there.  When
			building units, a unit may be built at any owned supply center.
		</p>
		<p>
			Author: Michel Ferion
		</p>]]></DESCRIPTION> 
		<MAP adjacencyURI="chaos_adjacency.xml">
			<MAP_GRAPHIC ref="chaos" default="true" />
		</MAP>
		<RULEOPTIONS>
			<RULEOPTION name="OPTION_BUILDS" value="VALUE_BUILDS_ANY_OWNED" />
		</RULEOPTIONS>
		
		<POWER name="Ankara" 	active="true" adjective="Ankaran" /> 
		<POWER name="Belgium" 	active="true" adjective="Belgian" /> 
		<POWER name="Berlin" 	active="true" adjective="Berliner" /> 
		<POWER name="Brest" 	active="true" adjective="Breton" />
		<POWER name="Budapest" 	active="true" adjective="Hungarian" /> 
		<POWER name="Bulgaria" 	active="true" adjective="Bulgarian" /> 
		<POWER name="Constantinople" active="true" adjective="Byzantine" /> 
		<POWER name="Denmark" 	active="true" adjective="Danish" /> 
		<POWER name="Edinburgh" active="true" adjective="Scottish" /> 
		<POWER name="Greece" 	active="true" adjective="Greek" /> 
		<POWER name="Holland" 	active="true" adjective="Dutch" /> 
		<POWER name="Kiel" 		active="true" adjective="Schleswiger" />
		<POWER name="Liverpool" active="true" adjective="Liverpudlian" /> 
		<POWER name="London" 	active="true" adjective="Cockney" /> 
		<POWER name="Marseilles" active="true" adjective="Marsellais" /> 
		<POWER name="Moscow" 	active="true" adjective="Muscovite" /> 
		<POWER name="Munich" 	active="true" adjective="Bavarian" /> 
		<POWER name="Naples" 	active="true" adjective="Neapolitan" />
		<POWER name="Norway" 	active="true" adjective="Norwegian" />
		<POWER name="Paris" 	active="true" adjective="Parisian" />
		<POWER name="Portugal" 	active="true" adjective="Portuguese" />
		<POWER name="Rome" 		active="true" adjective="Roman" />
		<POWER name="Rumania" 	active="true" adjective="Rumanian" />
		<POWER name="Serbia" 	active="true" adjective="Serbian" />
		<POWER name="Sevastopol" active="true" adjective="Crimean" />
		<POWER name="Smyrna" 	active="true" adjective="Smyrnan" />
		<POWER name="Spain" 	active="true" adjective="Spanish" />
		<POWER name="StPetersburg" active="true" adjective="St Petersburger" /> 
		<POWER name="Sweden" 	active="true" adjective="Swedish" /> 
		<POWER name="Trieste" 	active="true" adjective="Carinthian" /> 
		<POWER name="Tunis" 	active="true" adjective="Tunisian" /> 
		<POWER name="Venice" 	active="true" adjective="Venetian" /> 
		<POWER name="Vienna" 	active="true" adjective="Viennese" /> 
		<POWER name="Warsaw" 	active="true" adjective="Polish" /> 

		<STARTINGTIME turn="Fall, 1900, Adjustment" />
		<VICTORYCONDITIONS>
			<WINNING_SUPPLY_CENTERS value="18" />
			<YEARS_WITHOUT_SC_CAPTURE value="7" />
			<GAME_LENGTH value="35" />
		</VICTORYCONDITIONS>
		
 	 	<!-- supply centers -->
		<SUPPLYCENTER province="ank" owner="Ankara" 	/>
		<SUPPLYCENTER province="bel" owner="Belgium" 	/>
		<SUPPLYCENTER province="ber" owner="Berlin" 	/>
	 	<SUPPLYCENTER province="bre" owner="Brest" 	    />
		<SUPPLYCENTER province="bud" owner="Budapest" 	/>
		<SUPPLYCENTER province="bul" owner="Bulgaria" 	/>
	 	<SUPPLYCENTER province="con" owner="Constantinople" />
		<SUPPLYCENTER province="den" owner="Denmark" 	/>
		<SUPPLYCENTER province="edi" owner="Edinburgh"  />
		<SUPPLYCENTER province="gre" owner="Greece" 	/>
		<SUPPLYCENTER province="hol" owner="Holland" 	/>
		<SUPPLYCENTER province="kie" owner="Kiel" 		/>
		<SUPPLYCENTER province="lvp" owner="Liverpool"  />
		<SUPPLYCENTER province="lon" owner="London" 	/>
	 	<SUPPLYCENTER province="mar" owner="Marseilles" />
	 	<SUPPLYCENTER province="mos" owner="Moscow" 	/>
		<SUPPLYCENTER province="mun" owner="Munich" 	/>
	 	<SUPPLYCENTER province="nap" owner="Naples" 	/>
		<SUPPLYCENTER province="nor" owner="Norway" 	/>
	 	<SUPPLYCENTER province="par" owner="Paris" 	    />
		<SUPPLYCENTER province="por" owner="Portugal" 	/>
	 	<SUPPLYCENTER province="rom" owner="Rome" 		/>
		<SUPPLYCENTER province="rum" owner="Rumania" 	/>
		<SUPPLYCENTER province="ser" owner="Serbia" 	/>
	 	<SUPPLYCENTER province="sev" owner="Sevastopol" />
	 	<SUPPLYCENTER province="smy" owner="Smyrna" 	/>
		<SUPPLYCENTER province="spa" owner="Spain" 	    />
	 	<SUPPLYCENTER province="stp" owner="StPetersburg"  />
		<SUPPLYCENTER province="swe" owner="Sweden" 	/>
		<SUPPLYCENTER province="tri" owner="Trieste" 	/>
		<SUPPLYCENTER province="tun" owner="Tunis" 	    />
	 	<SUPPLYCENTER province="ven" owner="Venice" 	/>
		<SUPPLYCENTER province="vie" owner="Vienna" 	/>
	 	<SUPPLYCENTER province="war" owner="Warsaw" 	/>   
	</VARIANT>
</VARIANTS>
